name: E5 Public Client Renew

on:
  schedule:
    # Chạy 3 lần một ngày, khung giờ tản ra để tránh bị quét
    - cron: '15 2,10,18 * * *'
  workflow_dispatch:

jobs:
  run-auto-renew:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Random Delay
        run: sleep $((RANDOM % 1800))

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Cài đặt thư viện
        run: pip install requests pynacl

      - name: Chạy kịch bản
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: python auto_renew.py
